### ISSUE TITLE
updating while running is causes 'text file busy' error

### ISSUE THREAD

**Issue by wwar** [pingcap-incubator/tiup#102]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

This is two bugs in one:
- I ran `tidb update --nightly --all` (after having executed it only 5 minutes ago). I expect that it should be able to compare either modification date or checksum and not download a new file.

- Second bug is that it failed to update while a playground was running. This could be made more predictable by either refusing to update a running component, or moving the existing file before clobbering it:

```
$ tiup update --nightly --all
The component `client` does not have a nightly version; skipped.
The component `grafana` does not have a nightly version; skipped.
download https://tiup-mirrors.pingcap.com/pd-nightly-linux-amd64.tar.gz:
33213324 / 33213324 [----------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 14267940 p/s
Error: open /home/XXX/.tiup/components/pd/nightly/pd-server: text file busy
```

2. What did you expect to see?

* Check for actual updates
* Either refuse to upgrade, or fail predictably.

3. What did you see instead?

See above.

4. What version of TiUP are you using (`tiup --version`)?

```
tiup version v0.0.3 tiup
```

**Comment by lonng** [comment]
Fixed in tiup v0.0.4
