### ISSUE TITLE
Download progress indicator should be human formatted

### ISSUE THREAD

**Issue by wwar** [pingcap-incubator/tiup#103]
## Feature Request

**Is your feature request related to a problem? Please describe:**

The progress bars are useful, but on large files it is hard to see the size without formatting. i.e.

```
download https://tiup-mirrors.pingcap.com/pd-nightly-linux-amd64.tar.gz:
33213324 / 33213324 [-----------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 7776611 p/s
```

I believe the p/s should also be k/s.

**Describe the feature you'd like:**

It would be nice if it looked like this instead:

```
download https://tiup-mirrors.pingcap.com/pd-nightly-linux-amd64.tar.gz:
31.67 M / 31.67 M [-----------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 13.6 M/s
```

**Describe alternatives you've considered:**

I use gnome terminal, so I can see the sizes in human format by right clicking on them. But that is a bit of an inconvenience.. and not available to all users.

**Teachability, Documentation, Adoption, Migration Strategy:**

N/A, cosmetic change.

**Comment by lonng** [comment]
Closed via #152
