### ISSUE TITLE
The cluster cannot be shutdown properly when using nohup

### ISSUE THREAD

**Issue by HunDunDM** [pingcap-incubator/tiup#106]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Execute in terminal
``` bash
nohup tiup playground nightly >tiup.log 2>&1 &
echo "$\!" >tiup.pid
kill `cat tiup.pid`
```

2. What did you expect to see?

```
Got signal interrupt (Component: tidb ; PID: XXX)
Got signal interrupt (Component: tikv ; PID: XXX)
Got signal interrupt (Component: playground ; PID: XXX)
Got signal interrupt (Component: pd ; PID: XXX)
```

3. What did you see instead?

Only the playground was stopped normally. PD stopped unexpectedly, TiDB and TiKV are still running.
```
Got signal terminated (Component: playground ; PID: XXX)
Error: start `~/.tiup/components/pd/nightly/pd-server` (wd:~/.tiup/data/RvTgZcK/pd-0) failed: exit status 1
```
They cannot be stopped by `tiup clean --all`, only by `kill <PID>`.

4. What version of TiUP are you using (`tiup --version`)?
tiup version v0.0.3 tiup

**Comment by lonng** [comment]
Closed via #127
