### ISSUE TITLE
Failed to update self

### ISSUE THREAD

**Issue by BusyJay** [pingcap-incubator/tiup#137]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
$ tiup update --self
```

2. What did you expect to see?

Update successfully.

3. What did you see instead?

```
Error: download from https://tiup-mirrors.pingcap.com/tiup.sha1?v=1586783820365515632 failed: server returned 404 Not Found
```

4. What version of TiUP are you using (`tiup --version`)?

```
$ tiup --version
tiup version v0.0.4 tiup
Go Version: go1.13
Git Branch: master
GitHash: f74f86a
Build Time: 2020-04-10 15:01:40 +0800
```

**Comment by lonng** [comment]
@BusyJay Thanks for your report, this BUG had fixed via https://github.com/pingcap-incubator/tiup/pull/136. You must uninstall your tiup via `tiup uninstall --self` and re-download it again. I'm sorry for this case.
