### ISSUE TITLE
tiup should set `pd-server.metric-storage` automatically

### ISSUE THREAD

**Issue by BusyJay** [pingcap-incubator/tiup#144]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Deploy a cluster with default configuration except customize directory, IP and ports.

2. What did you expect to see?

Diagnose report from dashboard should work out of box.

3. What did you see instead?

> Error 1105: query metric error: [domain:9009]Prometheus address is not set in PD and etcd, Currently, the PD config `pd-server.metric-storage` value should be prometheus address, please check whether the config value is correct, you can use below sql check the value: select * from information_schema.cluster_config where type='pd' and `key` ='pd-server.metric-storage'; , you can use this shell command to set the config: `curl -X POST -d '{"metric-storage":"http://{PROMETHEUS_ADDRESS}"}' http://{PD_ADDRESS}/pd/api/v1/config`, PROMETHEUS_ADDRESS is the prometheus address, It's used for query metric data; PD_ADDRESS is the HTTP API address of PD server, all PD servers need to set this config. Here is an example: `curl -X POST -d '{"metric-storage":"http://127.0.0.1:9090"}' http://127.0.0.1:2379/pd/api/v1/config` 

4. What version of TiUP are you using (`tiup --version`)?

```
$ tiup --version
tiup version v0.0.4 tiup
Go Version: go1.13
Git Branch: master
GitHash: f74f86a
Build Time: 2020-04-10 15:01:40 +0800
```

**Comment by lonng** [comment]
@BusyJay Please update the `cluster` component, this BUG had been fixed.
`tiup update cluster` https://github.com/pingcap-incubator/tiup-cluster/pull/217

**Comment by BusyJay** [comment]
Verified it had not been fixed.
```
$ tiup --version
tiup version v0.0.4 tiup
Go Version: go1.13
Git Branch: master
GitHash: ee569fb
Build Time: 2020-04-13 21:22:39 +0800
```
```
$ tiup list
Available components (Last Modified: 2020-02-27T15:20:35+08:00):
Name               Installed    Platforms                 Description
----               ---------    ---------                 -----------
cluster            YES(v0.4.8)  darwin/amd64,linux/amd64  Deploy a TiDB cluster for production
```
