### ISSUE TITLE
tiup uninstall should not delete user data unless requested

### ISSUE THREAD

**Issue by BusyJay** [pingcap-incubator/tiup#150]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
```
tiup uninstall --self
curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh
```

2. What did you expect to see?
I can still access the cluster I setup previously.

3. What did you see instead?
```
tiup cluster stop example
Starting component `cluster`: /home/tidb/.tiup/components/cluster/v0.4.8/cluster stop stability

Error: cannot stop non-exists cluster example

Verbose debug logs has been written to /home/tidb/tiup-cluster-debug-2020-04-14-21-54-11.log.
Success to stop component `cluster`
Error: start `/home/tidb/.tiup/components/cluster/v0.4.8/cluster` (wd:/home/tidb/.tiup/data/Rw8p5YZ) failed: exit status 1
```

4. What version of TiUP are you using (`tiup --version`)?
```
$ tiup --version
tiup version v0.0.4 tiup
Go Version: go1.13
Git Branch: master
GitHash: ee569fb
Build Time: 2020-04-13 21:22:39 +0800
```

**Comment by lonng** [comment]
@BusyJay  The semantic of `tiup uninstall --self` is that delete all data and components.

**Comment by BusyJay** [comment]
Even desktop software has the option to whether to clean all the user data when uninstall. When you use yum/dnf/apt to delete a package, user configuration will also not be deleted. It's so confusing and dangerous to delete all data for tiup given that all progresses are still running in remote.

**Comment by lonng** [comment]
@BusyJay How about adding a flag to let users determine the behavior? e.g: `tiup uninstall --self --clean-data`

**Comment by BusyJay** [comment]
LGTM
