### ISSUE TITLE
Need `tiup history` to show command history

### ISSUE THREAD

**Issue by sykp241095** [pingcap-incubator/tiup#188]
## Feature Request

**Is your feature request related to a problem? Please describe:**

We ofter forget what we executed before, so we need a standalone `tiup history` to show history command beside shell history( shell history is really noisy), this could help debug a lot.

**Describe the feature you'd like:**

```shell
tiup history  # show history with a pager e.g.: `less` or `more` shell command
tiup history -100  # shows only latest 100 lines
tiup history > history.txt
```

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by AstroProfundis** [comment]
We have a similar sub command `audit` in `cluster`, could you confirm if that could fit your needs if we port that to `tiup`?
