### ISSUE TITLE
UCP: Support specify configuration file of TiDB/TiKV/PD when starting playground

### ISSUE THREAD

**Issue by lonng** [pingcap-incubator/tiup#64]
## Description

Currently, we cannot specify the configuration file for the internal component of the playground, we should support this feature.

e.g `tiup playground --db.config ~/conf/db.config.toml --kv.config ~/conf/kv.config.toml`

## Score

* 100

## Mentor(s)

* @lonng

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Go

**Comment by lonng** [comment]
@chenlx0 Sorry for that our bot hasn't been configured correctly, we have fixed it. Please pick this issue again.

**Comment by chenlx0** [comment]
Hi, i'd like to check some points here.

In the configuration file, we just need to specify host, port, status port and number of TiDB/TiKV/pd. Is that right?

**Comment by lonng** [comment]
The configuration file is specified by user, eg:
```
tiup playground --kv 3 --db 3 --pd 3 --pd.config ~/custom.pd.toml
```

This task allows the users to specify the configuration file for the specific component.
