### ISSUE TITLE
bug: can not install pd:v3.0.8

### ISSUE THREAD

**Issue by leoppro** [pingcap-incubator/tiup#67]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

run `tiup install pd:v3.0.8`

2. What did you expect to see?
`Error: component 'pd' doesn't release the version 'v3.0.8'`

3. What did you see instead?

installed successfully.

4. What version of TiUP are you using (`tiup --version`)?

`tiup version v0.0.2+Unknown(Unknown)`

**Comment by lonng** [comment]
@leoppro Thank you for your report, we have fixed it.
