### ISSUE TITLE
UCP: Support specifies the binary path when running a component

### ISSUE THREAD

**Issue by lonng** [pingcap-incubator/tiup#77]
## Description

Support specifies the binary path when running a component.

## Score

* 50

## Mentor(s)

* @lonng

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Go

**Comment by fredchenbj** [comment]
@lonng Hi, I would like check some points about this issue here.

Is the binary path specified like this, eg `tiup playground --kv 3 --db 3 --pd 3 --tidb.binpath /xx/tidb-server --tikv.binpath /xx/tikv-server --pd.binpath /xx/pd-server`

**Comment by lonng** [comment]
@fredchenbj I think it's OK.
