### ISSUE TITLE
Fail to run `tiup update --all`

### ISSUE THREAD

**Issue by Fullstop000** [pingcap-incubator/tiup#90]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
`tiup update --all`

2. What did you expect to see?

Update ok 

3. What did you see instead?
![image](https://user-images.githubusercontent.com/12471960/77847500-051b8200-71f0-11ea-99ad-2d34b48bb780.png)

4. What version of TiUP are you using (`tiup --version`)?

tiup version v0.0.2+Unknown(Unknown)

**Comment by Fullstop000** [comment]
It seems this happens only when downloading TiKV. The connection will be closed at a certain progress. 
![image](https://user-images.githubusercontent.com/12471960/77848413-07cda580-71f7-11ea-8722-130dfe7a5188.png)

**Comment by lonng** [comment]
We had adjusted CDN settings to avoid this case.
